/*******************************************************************************
 * Module      : Ultrasonic
 *
 * File Name   : ultrasonic.c
 *
 * Description : Source file for the Ultra_sonic driver
 *
 *
 * Author      : Abdlarhman Hesham
 *******************************************************************************/

#include "gpio.h"
#include "ultrasonic.h"
#include "icu.h"
#include "util/delay.h"

uint8 g_edgeCount = 0;  /*to count number of edges we need to calculate distance between*/
uint16 g_timeHigh = 0;  /*time taken to reach a block and back*/



/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*******************************************************************************
 * [Function Name] : Ultrasonic_init
 *
 * [Description]   : Initialize the ICU driver as required.
 * 					 Setup the ICU call back function.
 * 					 Setup the direction for the trigger pin as output pin through the GPIO driver
 *
 * [Args]          : NONE
 *******************************************************************************/
void Ultrasonic_init(void){
	/*configuration of the ICU driver*/
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	/*setting the call back function in the ICU driver*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/*initializing the ICU driver with the required configuration*/
	Icu_init(&Icu_Config);
	/*sitting the trigger pin to be output pin*/
	GPIO_setupPinDirection(TRIGGER_PORT,TRIGGER_PIN,PIN_OUTPUT);
	/*disabling trigger pin*/
	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN,LOGIC_LOW);

}

/*******************************************************************************
 * [Function Name] : Ultrasonic_edgeProcessing
 *
 * [Description]   : The call_back function called by the ICU driver.
 * 					 It's used to calculate the high time (pulse time)
 * 					 generated by the ultrasonic sensor.
 *
 * [Args]          : NONE
 *******************************************************************************/
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge as the first one was rising as chosen in ICU initialization*/
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		/*as here we only need to calculate pulse time between 2 edges*/
		g_edgeCount = 0;
	}

}

/*******************************************************************************
 * [Function Name] : Ultrasonic_Trigger
 *
 * [Description]   : Send the Trigger pulse to the ultrasonic
 *
 * [Args]          : NONE
 *******************************************************************************/
void Ultrasonic_Trigger(void){

	/*enabling trigger pin*/
	GPIO_writePin(TRIGGER_PORT,TRIGGER_PIN,LOGIC_HIGH);
	_delay_us(10);
	/*disabling trigger pin after a little delay(10 micro sec) to get the pin ready for a new trigger*/
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_LOW);

}

/*******************************************************************************
 * [Function Name] : Ultrasonic_readDistance
 *
 * [Description]   : Send the trigger pulse by using Ultrasonic_Trigger function.
 * 					 Start the measurements by the ICU from this moment and returning
 * 					 the measured distance.
 *
 * [Args]          : NONE
 * [Returns]       : Distance (The measured distance in Centimeter).
 *******************************************************************************/
uint16 Ultrasonic_readDistance(void){

	static uint16 distance;
	/*for calibrating the reading due to ultrasonic tolerance*/
	static uint16 distance_calibration;
	/*enabling triggering*/
	Ultrasonic_Trigger();

	/*  Sound velocity =   343.00 m/s = 34300 cm/s
	    The distance of Object (in cm) = (soundVelocity * TimerValue)/2
		Now, here we have selected an internal 8 MHz oscillator frequency for ATmega16, with 8_prescaler
		for timer frequency. Then time to execute 1 instruction is 1us.

		So, the timer gets incremented after 1us time elapse.

                 = 17150 x (TIMER value) x 1 x 10^-6 cm

                 = 1 x (TIMER value)*0.01715 cm                        */

	distance = g_timeHigh*0.01715+1; /* (+1) because of ultrasonic tolerence*/

	/*Also for calibration*/
	if(distance>=342){
		distance_calibration=distance+2;
		return distance_calibration;
	}
	else if(distance>=154){
		distance_calibration=distance+1;
		return distance_calibration;
	}

	else{
	return distance;}

	return 1;
}
